spec-version:        0.36.0
name:                aoc-hs
version:             0.1.0.0
github:              "tobeannouncd/aoc-hs"
license:             BSD-3-Clause
author:              "tobeannouncd"
maintainer:          "wzrds3@gmail.com"
copyright:           "2024 tobeannouncd"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tobeannouncd/aoc-hs#readme>

dependencies:
- base >= 4.7 && < 5

language: GHC2021

default-extensions:
- LambdaCase
- BlockArguments

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: solutions
  generated-other-modules: Paths_aoc_hs
  dependencies:
  - containers
  - parsec
  - linear
  - mtl
  - lens
  - array

executables:
  aoc-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-hs
    - optparse-applicative
    - time
    - text
    - advent-of-code-api
    - mtl
    - containers
    - criterion
